add functions for stepper PIN enabling and disabling
SouthEugeneRoboticsTeam/ursa pull request #41
Opened 2019-07-09 05:42 UTC by joshua255

making a pull request for @sambosch77's work, not ready to merge yet.

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +      void loop() {
a digitalWrite changes the pin and it won't change again until there is a new digital write. this void loop is uncecessary and is probably why the code won't compile

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +      pinMode(ENS_PIN GPIO_NUM_23, OUTPUT) // sets this PIN as an output
pinMode should be put in setup, and only needs to be called once

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +      void setupMotors() { // function turns on stepper motors using an enable PIN on the drivers
you are declaring the function void setupMotors inside the main loop, you can either delete the function and leave only the digitalWrite, or declare the function (with just a digital write inside) outside any other functions and then call it here. Also, using the name enableMotors would be more descriptive, keeping the name setupMotors if you want a function to set the pinmode to output in setup.

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +      digitalWrite(ENS_PIN GPIO_NUM_23, HIGH) // loop in place to make sure PIN stays enabled (not sure if necessary)
needs a semicolon at the end of this line (you're not in Kotlin anymore) :smile:

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +    pinMode(ENS_PIN GPIO_NUM_23, OUTPUT) // making sure that this is still recognized as an output (not sure if necessary)
like before, pinmode is unnecessary, it can be setup in void setup and then stays forever

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +    void turnOffMotors (){
you don't declare functions inside your other code, I would recommend not trying to make a function and just leaving a digital write here

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +    digitalWrite(ENS_PIN GPIO_NUM_23, LOW) // same with the turning on - making sure the steppers remain disabled
counter intuitively, the motor driver disables when the pin is pulled HIGH, not low.
you also need a semicolon

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +    void loop() {
like before, no loop is necessary

2019-07-09 06:00 UTC, joshua255 commented on ursa.ino
> +      digitalWrite(ENS_PIN GPIO_NUM_23, HIGH) // loop in place to make sure PIN stays enabled (not sure if necessary)
From a4988 datasheet: Enable Input - This input turns on or off all of the FET outputs. When set to a logic high, the outputs are disabled. When set to a logic low, the internal control enables the outputs as required.

2019-07-09 19:12 UTC, joshua255 commented on ursa.ino
> +      pinMode(ENS_PIN GPIO_NUM_23, OUTPUT) // sets this PIN as an output
One more thing, use just ENS_PIN to refer to the pin, it equals GPIO_NUM_23 which equals the number pin for the esp32 to change

2019-07-09 23:46 UTC, andrewda requested changes

2019-07-09 23:46 UTC, andrewda commented on ursa.ino
> +      // TODO: turn on stepper motors (complete?)
```suggestion
```

2019-07-09 23:46 UTC, andrewda commented on ursa.ino
> +    // TODO: turn off stepper motors (complete?)
```suggestion
```

2019-07-10 01:06 UTC, joshua255 commented
@SamBosh77 looks great! Just take Andrew's suggestion of removing comments and I think your're ready to merge!

2019-07-10 01:56 UTC, andrewda approved these changes
LGTM

2019-07-10 03:18 UTC, merged